language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO="django==1.5.1 --use-mirrors"
  - DJANGO="django==1.4.5 --use-mirrors"
  - DJANGO="django==1.3.7 --use-mirrors"

notifications:
  email: false

install:
  - pip install -r .travis-requirements.txt
  - pip install $DJANGO

script:
  - tests/runtests.py

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="django==1.4.5 --use-mirrors"
    - python: "3.2"
      env: DJANGO="django==1.3.7 --use-mirrors"
    - python: "3.3"
      env: DJANGO="django==1.4.5 --use-mirrors"
    - python: "3.3"
      env: DJANGO="django==1.3.7 --use-mirrors"
